###
### A complete description of a Prefect Deployment for flow 'All Leagues Complete ETL'
###
name: All Leagues
description: |-
  Complete all flow, but for all leagues.
  Args:
      queue (str): The queue type to filter for. (legal values: RANKED_SOLO_5x5, RANKED_FLEX_SR, RANKED_FLEX_TT)
      pages (int): The number of pages to return. (legal range: 1-100). (default: 1)
      regions (list[str]): A list of regions to filter for. Defaults to all regions if not specified.(legal values: ["ph2", "eun1", "euw1", "jp1", "kr", "la1", "la2", "na1", "oc1", "ru", "sg2", "th2", "tr1", "tw2", "vn2","br1"]).
      ACCOUNT_INPUT_LIMIT (int): The maximum number of account IDs to be sent to the API. Account IDs received from the API are not limited.(default: None)
      MATCH_INPUT_LIMIT (int): The maximum number of match IDs to be sent to the API. Match IDs received from the API are not limited.(default: None)
      API_KEYS (list[str]): A list of API keys to use for the request. If None, the program will use the API_KEYS provided in ../configs/flows_config.ini.  Useful if the user has an application API. (default: None)
      MAXIMUM_CONCURRENT_REQUESTS (int): The maximum number of concurrent requests to make. If instabilities or crashes occur, lower the maximum amount.(default: 100)
  Returns:
      None
version: 2e1a43c72189fcc3fd4777d53d17110f
# The work queue that will handle this deployment's runs
work_queue_name: default
work_pool_name: null
tags: []
parameters: {}
schedule: null
is_schedule_active: null
infra_overrides: {}
infrastructure:
  type: process
  env: {}
  labels: {}
  name: null
  command: null
  stream_output: true
  working_dir: null
  block_type_slug: process
  _block_type_slug: process

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: All Leagues Complete ETL
manifest_path: null
storage: null
path: D:\Educational Others\2023 Data Engineering Zoomcamp Project
entrypoint: flows\all_flows.py:etl_all_league
parameter_openapi_schema:
  title: Parameters
  type: object
  properties:
    queue:
      title: queue
      description: 'The queue type to filter for. (legal values: RANKED_SOLO_5x5,
        RANKED_FLEX_SR, RANKED_FLEX_TT)'
      position: 0
      type: string
    pages:
      title: pages
      description: 'The number of pages to return. (legal range: 1-100). (default:
        1)'
      default: 1
      position: 1
      type: integer
    regions:
      title: regions
      description: 'A list of regions to filter for. Defaults to all regions if not
        specified.(legal values: ["ph2", "eun1", "euw1", "jp1", "kr", "la1", "la2",
        "na1", "oc1", "ru", "sg2", "th2", "tr1", "tw2", "vn2","br1"]).'
      position: 2
      type: array
      items:
        type: string
    ACCOUNT_INPUT_LIMIT:
      title: ACCOUNT_INPUT_LIMIT
      description: 'The maximum number of account IDs to be sent to the API. Account
        IDs received from the API are not limited.(default: None)'
      position: 3
      type: integer
    MATCH_INPUT_LIMIT:
      title: MATCH_INPUT_LIMIT
      description: 'The maximum number of match IDs to be sent to the API. Match IDs
        received from the API are not limited.(default: None)'
      position: 4
      type: integer
    API_KEYS:
      title: API_KEYS
      description: 'A list of API keys to use for the request. If None, the program
        will use the API_KEYS provided in ../configs/flows_config.ini.  Useful if
        the user has an application API. (default: None)'
      position: 5
      type: array
      items:
        type: string
    MAXIMUM_CONCURRENT_REQUESTS:
      title: MAXIMUM_CONCURRENT_REQUESTS
      description: 'The maximum number of concurrent requests to make. If instabilities
        or crashes occur, lower the maximum amount.(default: 100)'
      default: 100
      position: 6
      type: integer
  required:
  - queue
  definitions: null
timestamp: '2023-04-10T03:48:49.473782+00:00'
